#!/usr/bin/env ruby
require 'colorize' # Colorized Line

$regex =  /^\(#[0-9]+\)\s[\d\D]*/

# enforced custom commit message format
def check_message_format
  message_file = ARGV[0]
  message = File.read(message_file)

  if !$regex.match(message)
      puts "!!Caution!! It violates the commit message rules.".red # If you dont wanna be colorized console, delete .red
      puts ""
      puts "[Rules]"
      puts "Variables : ##Variable##".blue # If you dont wanna be colorized console, delete .blue
      puts ""
      puts "(###IssueNumber##) ##Commit Message##"
      puts ""
      puts "Example".blue # If you dont wanna be colorized console, delete .blue
      puts "(#152) Initial Commit"
      exit 1
  end
end

check_message_format
